name: Rust

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: cargo test
